import { Link } from 'react-router-dom'
import { ArrowRight, Sparkles, Target, TrendingUp } from 'lucide-react'

export function Landing() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-900 via-slate-900 to-cyan-950/30">
      <header className="border-b border-slate-700/50 px-4 py-4 md:px-8">
        <div className="mx-auto flex max-w-6xl items-center justify-between">
          <div className="flex items-center gap-2">
            <img src="/favicon.svg" alt="" className="h-8 w-8" aria-hidden />
            <span className="text-xl font-semibold text-white">AI Survival Radar</span>
          </div>
          <Link
            to="/login"
            className="rounded-lg bg-cyan-500 px-4 py-2 text-sm font-medium text-slate-900 transition hover:bg-cyan-400"
          >
            Sign in
          </Link>
        </div>
      </header>

      <section className="mx-auto max-w-4xl px-4 py-16 text-center md:py-24">
        <h1 className="text-4xl font-bold tracking-tight text-white md:text-5xl lg:text-6xl">
          Stay competitive in the{' '}
          <span className="bg-gradient-to-r from-cyan-400 to-teal-400 bg-clip-text text-transparent">
            AI economy
          </span>
        </h1>
        <p className="mt-6 text-lg text-slate-400 md:text-xl">
          Personalized learning paths, AI-generated syllabi, and progress tracking so you can thrive as AI transforms work.
        </p>
        <div className="mt-10 flex flex-wrap items-center justify-center gap-4">
          <Link
            to="/login"
            className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-6 py-3.5 text-base font-semibold text-slate-900 shadow-lg shadow-cyan-500/25 transition hover:bg-cyan-400 hover:shadow-cyan-500/30"
          >
            Get started
            <ArrowRight className="h-5 w-5" aria-hidden />
          </Link>
          <Link
            to="/login"
            className="inline-flex items-center gap-2 rounded-xl border border-slate-600 bg-slate-800/50 px-6 py-3.5 text-base font-medium text-slate-200 transition hover:bg-slate-800"
          >
            Sign in with Google
          </Link>
        </div>
      </section>

      <section className="mx-auto max-w-5xl px-4 py-16 md:py-24">
        <div className="grid gap-8 md:grid-cols-3">
          <div className="rounded-2xl border border-slate-700/50 bg-slate-800/30 p-6 text-left">
            <Sparkles className="h-10 w-10 text-cyan-400" aria-hidden />
            <h2 className="mt-4 text-lg font-semibold text-white">AI-powered syllabi</h2>
            <p className="mt-2 text-slate-400">
              Each skill gets a curriculum tailored to your goal and level, generated by AI.
            </p>
          </div>
          <div className="rounded-2xl border border-slate-700/50 bg-slate-800/30 p-6 text-left">
            <Target className="h-10 w-10 text-cyan-400" aria-hidden />
            <h2 className="mt-4 text-lg font-semibold text-white">Track progress</h2>
            <p className="mt-2 text-slate-400">
              Reflections, achievements, and streaks keep you motivated and on track.
            </p>
          </div>
          <div className="rounded-2xl border border-slate-700/50 bg-slate-800/30 p-6 text-left">
            <TrendingUp className="h-10 w-10 text-cyan-400" aria-hidden />
            <h2 className="mt-4 text-lg font-semibold text-white">News & tools</h2>
            <p className="mt-2 text-slate-400">
              Finland intel, global trends, and trending AI tools in one place.
            </p>
          </div>
        </div>
      </section>

      <footer className="border-t border-slate-700/50 px-4 py-8 text-center text-sm text-slate-500">
        AI Survival Radar — Build the skills that matter.
      </footer>
    </div>
  )
}
